### PR TITLE
Add sound notification

### PR DESCRIPTION
**Pull request by Athozus**
This is a PR which adds a sound notification, and its setting of course. I used the same "ding-dong" as the one in `unified_inventory` when you set your home. It is taken from https://freesound.org/people/bennstir/sounds/81072/ (I added the author in both README and about.lua). The code addition is kind of trivial (just a check for the setting and it plays). Tell me your feedback ;)

### CODE REVIEW

**Comment by S-S-X** [comment]
My opinion about selected sound: way too long. I'd say attack-sustain (first attack to last beginning of release) should be over in 0.5-2 seconds and release shouldn't last over 1 seconds. From beginning to end I'd say 2 - 2,5 seconds is absolute maximum for default notification sound.

**Comment by Athozus** [comment]
Ok, why not for the proposed sound. But I think it has to be something heard. At least, if you doesn't like the sound, you uncheck it.

**Comment by S-S-X** [comment]
Just saying that there's a reason why default notification sound for nearby every email, sms and chat applications are closer to 0.5-2 seconds than 3-5 seconds.

**Comment by Athozus** [comment]
I think this one could also be good : https://invent.kde.org/plasma-mobile/plasma-mobile-sounds/-/blob/master/plasma-mobile/stereo/notifications/Doorbell.oga

**Comment by S-S-X** [comment]
> I think those could also be good :
> 
> * https://invent.kde.org/plasma-mobile/plasma-mobile-sounds/-/blob/master/plasma-mobile/stereo/notifications/Doorbell.oga
> * https://invent.kde.org/plasma/oxygen-sounds/-/blob/master/sounds/Oxygen-Im-Nudge.ogg
> * https://invent.kde.org/plasma/oxygen-sounds/-/blob/master/sounds/Oxygen-Im-Sms.ogg
> * https://invent.kde.org/plasma/oxygen-sounds/-/blob/master/sounds/Oxygen-Im-New-Mail.ogg

My opinion, either Oxygen-Im-New-Mail.ogg or Doorbell.oga, maybe Oxygen-Im-Nudge.ogg

But I think Doorbell.oga hits roof and there's some clipping, doesn't exactly sound clean but there's some cracks and might need editing.

Also all but Oxygen-Im-Nudge.ogg (which has additional stereo effect) or Doorbell.oga are biased toward right channel, didn't actually check but sounds like that for me.

Just trying to listen I think Oxygen-Im-Nudge.ogg is only one that is actually clean, Doorbell.oga isn't too bad but not clean.

**Comment by Athozus** [comment]
> Just trying to listen I think Oxygen-Im-Nudge.ogg is only one that is actually clean, Doorbell.oga isn't too bad but not clean.

So, we keep Nudge ?

**Comment by S-S-X** [comment]
> > Just trying to listen I think Oxygen-Im-Nudge.ogg is only one that is actually clean, Doorbell.oga isn't too bad but not clean.
> 
> So, we keep Nudge ?

Works for me, I think that's best option so far (without some additional work / editing).

**Pull request merged**
