### PR TITLE
Fix crash if non-existent mail was selected

### PR DESCRIPTION
**Pull request by savilli**

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]
Didn't but lgtm 👍

**Review by S-S-X — APPROVED** [review]
Looks good but didn't test.

**Comment by Athozus** [comment]
Maybe do the same thing for outbox/.. ? Anyway, great work done :+1:

**Comment by savilli** [comment]
> Maybe do the same thing for outbox

Done

**Comment by Athozus** [comment]
Thx, great addition =) :+1:

**Pull request merged**
