### PR TITLE
Update translation templates

### PR DESCRIPTION
**Pull request by Niklp09**
- Used the new [engine tool](https://github.com/minetest/minetest/blob/master/util/mod_translation_updater.py).
- I'll update the german translation in another PR.

### CODE REVIEW

**Comment by Athozus** [comment]
Does it keeps the existing keywords ? And it just generates `.tr` that are retrocompatible with 5.0 I hope ?

**Comment by Niklp09** [comment]
> Does it keeps the existing keywords ?

If the key doesn't change yeah

> And it just generates .tr that are retrocompatible with 5.0 I hope ?

sorry, I don't understand... How could a .tr file not be 5.0 compatible?

**Comment by Athozus** [comment]
> sorry, I don't understand... How could a .tr file not be 5.0 compatible?

I mean, is it still a `.tr` file ? Because if it is not this format, it will not be compatible with older version.

**Comment by Niklp09** [comment]
> I mean, is it still a .tr file ? Because if it is not this format, it will not be compatible with older version.

why shouldn't it be a .tr file? There is no other translation format.

**Comment by Athozus** [comment]
> why shouldn't it be a .tr file? There is no other translation format.

Ok ok, that's fine. I was just afraid =)

**Pull request merged**
