### PR TITLE
Add support for a get_keys() equivalent for lower than 5.7 Minetest versions

### LINKED ISSUE #152: StorageRef:get_keys() is a nil value
2024-08-06 08:52:02: ERROR[Main]: ModError: Failed to load and run script from .../worldmods/mail/init.lua: 
2024-08-06 08:52:02: ERROR[Main]: .../worldmods/mail/migrate.lua:160: attempt to call method 'get_keys' (a nil value)
2024-08-06 08:52:02: ERROR[Main]: stack traceback:
2024-08-06 08:52:02: ERROR[Main]: .../worldmods/mail/migrate.lua:160: in function 'repair_storage'
2024-08-06 08:52:02: ERROR[Main]: .../worldmods/mail/migrate.lua:190: in function 'migrate' 
2024-08-06 08:52:02: ERROR[Main]: .../worldmods/mail/init.lua:58: in main chunk

### PR DESCRIPTION
**Pull request by Athozus**
Fix #152 

@MoNTE48 can you confirm me that it works ?

Notes :
- It checks if `get_keys()` exists
- Then, if not, it iterates through existing players (but consume more)
- I've also reorganized into more functions to not have too much duplicates

### CODE REVIEW

**Comment by MoNTE48** [comment]
@luk3yx

**Comment by Athozus** [comment]
Btw, normally until the repair hasn't finished, it is still noted as `v3`, but be sure that it is in order to run the repair. And do a backup, as I don't really want to break my Minetest by regressing version :grin: .

**Review by luk3yx — COMMENTED** [review]
There's another call to `mail.storage:get_keys()` in `is_uuid_existing` without a check that causes a crash.

**Comment by Athozus** [comment]
Is it okay now @luk3yx ?

**Comment by luk3yx** [comment]
It works now, thanks!

**Pull request merged**
